server:
  port: 8084

logging:
  level:
    org:
      springframework:
        security: INFO
    com:
      example:
        demo:
          apunte17: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://labsys.frc.utn.edu.ar/aim/realms/backend-tps"

